name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Packages
      run: |
        sudo apt install make git build-essential binutils-mips-linux-gnu python3 python3-pip
        python3 -m pip install -r requirements.txt

    - name: Get Dependencies
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.SECRETREPO }}
        token: ${{ secrets.SECRETREPOKEY }}
        path: deps_repo

    - name: Build Dependencies
      run: cp deps_repo/pokestadium/* .

    - name: Setup
      run: make setup

    - name: Build
      run: make

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
